env:
  global:
  - HUGO_VERSION=0.42.1
install: make install
script: make build
deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
  edge: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out github_deploy_key -d
- chmod 600 github_deploy_key
- eval $(ssh-agent -s)
- ssh-add github_deploy_key
