env:
  global:
  - HUGO_VERSION=0.42.1
install: "make install"
script: "make build"
deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_94d59ec4a7b9_key -iv $encrypted_94d59ec4a7b9_iv
  -in github_deploy_key_travis_basketball_singen.enc -out github_deploy_key_travis_basketball_singen
  -d
- chmod 600 github_deploy_key_travis_basketball_singen
- eval $(ssh-agent -s)
- ssh-add github_deploy_key_travis_basketball_singen
